name: Doxygen Wiki workflow

on:
  push:
    branches: [doc]

env:
  WORKFLOW_FILE_PATH: ".github/workflows/documentation.yml"

jobs:
  doxygen-generation:
    name: Doxygen HTML Generation, Commit, Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: checkout-respoitory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history

      - name: cache-doxygen-dependencies
        uses: actions/cache@v4
        env:
          cache-name: apt-doxygen-v1
        with:
          path: |
            /var/cache/apt/archives
            /var/lib/apt/lists
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles(env.WORKFLOW_FILE_PATH)}}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}

      - name: Install Doxygen and Graphviz
        run: |
          sudo apt-get update -q
          apt-cache policy doxygen
          sudo apt-get install -y doxygen graphviz

      - name: Run Doxygen
        run: |
          mkdir -p ./docs
          doxygen Doxyfile
          echo "Doxygen HTML output generated in ./docs"
