name: Doxygen Wiki workflow

on:
  push:
    branches: [doc]

env:
  WORKFLOW_FILE_PATH: ".github/workflows/documentation.yml"

jobs:
  doxygen-generation:
    name: Doxygen HTML Generation, Commit, Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: checkout-respoitory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history

      - name: cache-doxygen-dependencies
        uses: actions/cache@v4
        env:
          cache-name: apt-doxygen-v1
        with:
          path: |
            /var/cache/apt/archives/*.deb
            /var/lib/apt/lists
            !/var/cache/apt/archives/lock # Exclude lock file
            !/var/cache/apt/archives/partial # Exclude partial directory
            !/var/lib/apt/lists/lock    # Exclude lock file
            !/var/lib/apt/lists/partial # Exclude partial directory
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles(env.WORKFLOW_FILE_PATH)}}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}

      - name: Install Doxygen and Graphviz
        run: |
          sudo apt-get update -q
          apt-cache policy doxygen
          sudo apt-get install -y doxygen graphviz

      - name: Run Doxygen
        run: |
          mkdir -p ./docs
          doxygen Doxyfile
          echo "Doxygen HTML output generated in ./docs"

      - name: Clean APT caches
        run: |
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/partial/*
          sudo rm -f /var/lib/apt/lists/*lock
          sudo rm -f /var/cache/apt/archives/*lock
          # Make sure this runs even if previous steps fail, to ensure cache save doesn't fail
          # CRITICAL: Change permissions of the 'partial' directory itself
          # This ensures the 'runner' user can traverse into it, even if empty
          sudo chmod 755 /var/lib/apt/lists/partial || true
          sudo chmod 755 /var/cache/apt/archives/partial || true
        if: always()
